{
    'name': 'Cr Web Portal',
    'summary': 'Cr Web Portal',
    'description': 'Cr Web Portal',
    'category': 'Web',
    'version': '16.0.0.1',
    'depends': ['base', 'web', 'website_sale', 'auth_signup', 'portal', 'sale', 'website_blog', 'product', 'crm',
                'digest','mechpower_base_extended', 'spreadsheet','website_sale_stock','web_editor','purchase',
                'base_address_extended', 'mail', 'mass_mailing','payment','account','l10n_in'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/demo.xml',
        'data/data.xml',
        'data/mail_templates.xml',
        'data/digest_data.xml',
        'data/attchment_data.xml',
        'data/utm_source_data.xml',
        'templates/portal_sidebar.xml',
        'templates/portal_my_messages.xml',
        'templates/dynamic_blog.xml',
        'templates/website_layout.xml',
        'templates/login.xml',
        'templates/homepage.xml',
        'templates/about_us.xml',
        'templates/powervis.xml',
        'templates/enclosure_design.xml',
        'templates/3d_printing.xml',
        'templates/sheet_metal_fabrication.xml',
        'templates/cnc_machinig.xml',
        'templates/injection_molding.xml',
        'templates/customer_question_answer_form.xml',
        'templates/contact_us_page.xml',
        'templates/website_products.xml',
        'templates/instant_quote.xml',
        'templates/website_sale_address.xml',
        'templates/portal_my_account.xml',
        'templates/portal_account_address.xml',
        'templates/website.xml',
        'templates/blog.xml',
        'templates/portal_breadcrumb.xml',
        'templates/variant_mixin.xml',
        'templates/cart_design.xml',
        'templates/portal_sidebar_view.xml',
        'templates/extra_info_template.xml',
        'templates/privacy_policy.xml',
        'templates/blog_post_service.xml',
        'templates/signature_icons.xml',
        'templates/my_security.xml',
        'templates/my_security.xml',
        'templates/invoice_portal_doc.xml',
        'static/src/snippets/s_table_of_content_snippet.xml',

        'views/document_history_tree_view.xml',
        'views/invoice_view.xml',
        'views/product_image.xml',
        'views/payment_term.xml',
        'views/crm_view.xml',
        'views/payment_provider.xml',
        'views/product.xml',
        'views/industry_segment.xml',
        'views/sale_order_view.xml',
        'views/res_partner.xml',
        'views/project_task.xml',
        'views/purchase_tree_view.xml',
        'views/helpdesk_ticket.xml',
        'views/digest_digest.xml',
        'views/res_config_settings_views.xml',
        'views/res_city_views.xml',
        'views/mailing_mailing_views.xml',
        'views/service_cost.xml',
        'wizard/crm_lead_to_opportunity.xml',
        'report/ir_actions_report.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'cr_web_portal/static/src/js/my_message.js',
            'cr_web_portal/static/lib/aos.js',
            'cr_web_portal/static/src/js/3d_viewer.js',
            'cr_web_portal/static/src/js/advance_payment.js',
            'cr_web_portal/static/lib/swiper.min.js',
            'cr_web_portal/static/src/js/scripts.js',
            'cr_web_portal/static/src/js/validation.js',
            'cr_web_portal/static/src/js/industry_segment_validation.js',
            'cr_web_portal/static/src/js/website.js',
            'cr_web_portal/static/src/js/main.js',
            'cr_web_portal/static/src/js/website_blog.js',
            'cr_web_portal/static/src/js/variant_mixin.js',
            'cr_web_portal/static/src/js/website_sale_stock_variant_mixin.js',
            'cr_web_portal/static/src/js/portal_inquiery.js',
            'cr_web_portal/static/src/js/price_range_attribute.js',
            'cr_web_portal/static/src/js/signature_form.js',
            'cr_web_portal/static/src/js/profile_iimage.js',
            'cr_web_portal/static/src/js/website_billing_address.js',
            'cr_web_portal/static/src/js/blog_searchbar.js',
            'cr_web_portal/static/src/js/reorder.js',
            'cr_web_portal/static/lib/owlcarousel/owl.carousel.min.js',
            'cr_web_portal/static/src/js/carousel.js',
            'cr_web_portal/static/src/js/payment_form.js',
            'cr_web_portal/static/src/snippets/s_website_form/s_website_form.js',
            'cr_web_portal/static/src/js/mp_website.js',

            'cr_web_portal/static/src/scss/header_footer.scss',
            'cr_web_portal/static/src/scss/portal_invoice.scss',
            'cr_web_portal/static/src/scss/my_messages.scss',
            'cr_web_portal/static/src/scss/responsive.scss',
            'cr_web_portal/static/src/scss/shortcode.scss',
            'cr_web_portal/static/src/scss/style.scss',
            'cr_web_portal/static/src/scss/base.scss',
            'cr_web_portal/static/src/scss/index.scss',
            'cr_web_portal/static/src/scss/swiper.min.scss',
            'cr_web_portal/static/src/scss/service.scss',
            'cr_web_portal/static/lib/owlcarousel/assets/owl.carousel.min.css',
            'cr_web_portal/static/src/scss/homepage.scss',
            'cr_web_portal/static/src/scss/contactus.scss',
            'cr_web_portal/static/src/scss/privacy_policy.scss',
            'cr_web_portal/static/src/scss/about_us.scss',
            'cr_web_portal/static/src/scss/refurbish_style.scss',
            'cr_web_portal/static/src/scss/mp_website.scss',
            'cr_web_portal/static/src/scss/portal.scss',
            'cr_web_portal/static/src/scss/new_portal.scss',

            'cr_web_portal/static/src/xml/attachment_files.xml',
            'cr_web_portal/static/src/xml/website_sale_stock_product_availability.xml',
            # 'cr_web_portal/static/src/xml/payment_post_processing.xml',
        ],
        'web.assets_backend': [
            'cr_web_portal/static/src/xml/binary_field.xml',
            'cr_web_portal/static/src/js/binary_field.js',
            'cr_web_portal/static/src/js/dates.js',
            'cr_web_portal/static/src/js/searchmodel.js',
            'cr_web_portal/static/src/xml/chatter_topbar.xml',
        ],
        'spreadsheet.o_spreadsheet': [
            'cr_web_portal/static/src/js/dashboard_filter.js',
        ],
        'website.assets_editor': [
            'cr_web_portal/static/src/xml/seo.xml',
        ],
        'web_editor.assets_wysiwyg': [
            'cr_web_portal/static/src/xml/dynamix_font_size.xml',
            'cr_web_portal/static/src/scss/fontsize_snippet.scss',
             'cr_web_portal/static/src/js/odooeditor.js',
        ],
    },
    'application': False,
    'license': 'LGPL-3',
}
