from . import res_partner
from . import close_reason
from . import sale_order
from . import customer_files
from . import stock
from . import product_template
from . import mail_thread
from . import project
from . import mail_wizard_invite
from . import helpdesk
from . import crm
from . import ir_mail_server
from . import purchase