# -*- coding: utf-8 -*-
from . import invoice
from . import crm
from . import mail_message
from . import product
from . import sale_order
from . import res_partner
from . import industry_segment
from . import website
from . import blog_post_service
from . import signature_icons
from . import document_history
from . import ir_attachment
from . import product_image
from . import model
from . import digest
from . import payment_transaction
from . import helpdesk_ticket
from . import res_config_settings
from . import product_attribute
from . import service_cost
from . import purchase_order